### ISSUE TITLE
The client is failing at handling results from project 'mclogs' 🤦

### ISSUE THREAD

**Issue by mikkolukas** [aternosorg/php-modrinth-api#12]
Using your client, running the sample code from the README, it fails to handle the result for your own modrinth project 'mclogs':

Can be simplified to this call: `$modrinthClient->getProject('mclogs');`

```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid value 'unknown' for 'client_side', must be one of 'required', 'optional', 'unsupported' in /home/u/repos/.../vendor/aternos/modrinth-api/lib/Model/Project.php:884
Stack trace:
#0 /home/u/repos/.../vendor/aternos/modrinth-api/lib/ObjectSerializer.php(542): Aternos\ModrinthApi\Model\Project->setClientSide()
modrinth/labrinth#1 /home/u/repos/.../vendor/aternos/modrinth-api/lib/Api/ProjectsApi.php(2941): Aternos\ModrinthApi\ObjectSerializer::deserialize()
modrinth/labrinth#2 /home/u/repos/.../vendor/aternos/modrinth-api/lib/Api/ProjectsApi.php(2862): Aternos\ModrinthApi\Api\ProjectsApi->getProjectWithHttpInfo()
modrinth/labrinth#3 /home/u/repos/.../vendor/aternos/modrinth-api/lib/Client/ModrinthAPIClient.php(184): Aternos\ModrinthApi\Api\ProjectsApi->getProject()
modrinth/labrinth#4 /home/u/repos/.../public/index.php(4): Aternos\ModrinthApi\Client\ModrinthAPIClient->getProject()
modrinth/labrinth#5 {main}
  thrown in /home/u/repos/.../vendor/aternos/modrinth-api/lib/Model/Project.php on line 884
```

---

Failing at even the simplest command does not bode well for this client. I will go look somewhere else or just build my own. This is not a serious project and it should have a disclaimer at the top of the README saying that.

**Comment by JulianVennen** [comment]
Hi, this is a known problem with the Modrinth API: https://github.com/modrinth/code/issues/2590

The API spec does not specify an "unknown" option for this value and the OpenAPI generator does not allow unknown values.
IIRC modrinth has some larger issue with sides behind the scenes so if they can't fix this in the near future we may need to fork their API spec.

**Comment by mikkolukas** [comment]
Would be worth mentioning in the README then - or at least not provide a sample project that have a failing result.

**Comment by JulianVennen** [comment]
The README is not the modrinth API bug tracker

**Comment by mikkolukas** [comment]
True that, but it taints your solution, when the "getting started" section of your readme leads a new user directly into an exception - without telling the users that this is expected behavior.

I can now clearly see why your solution does that, but not mentioning that the given example will break is just as bad as pointing people towards the train station, in a direction that crosses a bridge you already know is rotten and will break under their feet - but not mentioning that to them along with the direction.

**Comment by JulianVennen** [comment]
The library now uses a fork of the Modrinth API spec, which contains this enum value.
I also created a PR to upstream this change in the documentation: https://github.com/modrinth/docs/pull/156
